sonar.projectKey=eslint-sonar-integration
sonar.projectName=eslint-sonar-integration
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.eslint.reportPaths=eslint-report.json
sonar.exclusions=node_modules/**
